"use strict";

const TRANSLATIONS = {
    id: {
        appTitle: 'Absensi Piket Kelas',
        setupTitle: 'ABSENSI PIKET KELAS',
        setupStudentDesc: 'Tambahkan semua siswa yang akan dikenali oleh sistem.\n                Setiap siswa cukup memiliki satu foto wajah yang jelas.',
        promptAddStudent: 'Masukkan nama lengkap siswa:',
        duplicateStudent: 'Nama siswa tersebut sudah terdaftar.',
        settingsNeedStudent: 'Tambahkan minimal satu siswa.',
        missingFaceConfirm: 'Siswa berikut belum memiliki foto wajah:\n\n{names}\n\nTetap simpan pengaturan?',
        settingsNeedSchedule: 'Pilih minimal satu siswa untuk jadwal piket.',
        settingsSaveError: 'Pengaturan gagal disimpan ke database browser.\n\n{message}',
        settingsSavedToast: 'Pengaturan tersimpan. Membuka kamera…',
        flashUnsupported: 'Flash tidak didukung perangkat ini.',
        resumeAttendance: 'Absen piket belum selesai.\n\nYuk lanjutkan lagi ya 🙂',
        openDbError: 'Gagal membuka database browser.',
        sizeTooLarge: 'Ukuran foto terlalu besar. Maksimal 15 MB sebelum dikompres.',
        exit: 'Keluar',
        noStudents: 'Belum ada siswa.',
        photoRegistered: '✓ Foto wajah terdaftar',
        photoMissing: '⚠ Foto wajah belum ada',
        changePhoto: 'Ganti Foto',
        addPhoto: 'Tambah Foto',
        confirmDeleteStudent: 'Hapus siswa "{name}"?',
        studentLabel: 'Siswa: {name}',
        chooseFacePhoto: 'Pilih 1 foto wajah yang jelas<br>dengan rasio 1:1',
        choosePhotoFirst: 'Pilih foto wajah terlebih dahulu.',
        fileMustBeImage: 'File harus berupa gambar.',
        processLoadAI: '⏳ Memuat AI…',
        processPreparePhoto: '⏳ Menyiapkan foto…',
        processAnalyzeFace: '⏳ Menganalisis wajah…',
        errorFaceNotDetected: 'Wajah tidak terdeteksi.',
        errorOneFace: 'Foto harus menampilkan tepat satu wajah.',
        errorEmbedding: 'Embedding wajah tidak berhasil dibuat.',
        errorEmbeddingFormat: 'Format embedding wajah tidak valid. Coba simpan foto lagi.',
        errorFaceQuality: 'Kualitas deteksi wajah terlalu rendah.',
        errorPhotoRead: 'Foto tidak dapat dibaca oleh browser.',
        errorPhotoProcess: 'Wajah tidak berhasil diproses.',
        successPhoto: 'Foto wajah {name} berhasil didaftarkan dengan AI Human. ✓',
        studentSetupRequired: 'Tambahkan siswa terlebih dahulu.',
        noFacePhoto: '⚠ Belum ada foto wajah',
        cameraRatioAria: 'Pengaturan rasio kamera',
        ratioPortrait: '9:16 — Portrait',
        ratioLandscape: '16:9 — Landscape',
        emptySchedule: 'Tambahkan siswa terlebih dahulu.',
        resultSave: 'Simpan & Selesai',
        savingReport: 'Menyimpan laporan…',
        reportUnavailableNow: 'Data hasil absensi belum tersedia. Silakan ambil foto lagi.',
        reportSaveError: 'Laporan absensi gagal disimpan.',
        resetWarningTitle: 'PERINGATAN!',
        resetWarningBody: 'Semua data siswa, foto wajah, jadwal, PIN Ruang Guru, laporan, dan foto bukti akan dihapus dari perangkat ini.',
        resetContinue: 'Lanjutkan?',
        resetFacesBody: 'Data wajah siswa juga akan dihapus.',
        resetConfirm: 'Yakin benar-benar ingin menghapus semuanya?',
        resetSuccess: 'Semua data berhasil dihapus.',
        cameraErrorTitle: '📷 Kamera belum dapat digunakan',
        preparingCamera: 'Kamera sedang dipersiapkan…',
        cameraStartMessage: 'Kamera belum dapat dimulai. Periksa izin kamera browser.',
        cameraErrorText: 'Izinkan akses kamera untuk melanjutkan absensi.',
        cameraClose: 'Tutup',
        cameraPermission: 'Izinkan Akses Kamera',
        cameraPermissionText: 'Izin kamera hanya dapat diberikan pada halaman HTTPS atau localhost. File HTML yang diunduh tidak dapat melewati pembatasan keamanan browser.',
        cameraPermissionDenied: 'Izin kamera diblokir. Buka pengaturan izin situs pada browser, ubah Kamera menjadi Izinkan, lalu kembali dan tekan Coba Lagi. Di iPhone/iPad, periksa Pengaturan > Safari > Kamera.',
        cameraBusyError: 'Kamera sedang digunakan oleh aplikasi lain. Harap matikan Video Call (WhatsApp/Zoom) atau tutup aplikasi kamera lain, lalu refresh halaman ini.',
        cameraLegacyFallback: 'Browser ini tidak menyediakan API kamera live. Gunakan browser modern (Chrome, Edge, atau Safari) dan buka aplikasi melalui HTTPS/localhost.',
        cameraPrivateMode: 'Anda mungkin berada di Mode Samaran/Privasi. Beberapa fitur offline dan PWA mungkin tidak berfungsi normal.',
        cameraVirtualError: 'Kamera virtual atau kamera palsu terdeteksi. Gunakan kamera bawaan perangkat untuk melanjutkan absensi.',
        cameraPrivacyError: 'Sistem privasi, extension, atau browser memblokir hasil pengambilan gambar. Matikan Shields/AdBlock untuk halaman ini atau gunakan browser utama.',
        cameraIframeError: 'Kamera dibuka di dalam iframe. Portal sekolah harus memberi izin camera pada iframe. Gunakan atribut: allow="camera; autoplay; fullscreen".',
        cameraIframeTitle: 'Kamera dalam iframe',
        cameraIframeText: 'Aplikasi sedang dibuka di dalam iframe. Portal sekolah harus mengizinkan kamera pada tag iframe agar kamera live dapat digunakan.',
        cameraUpdateTitle: 'Versi web terbaru tersedia',
        cameraUpdateText: 'Versi terbaru aplikasi absensi sudah siap. Perbarui halaman agar perubahan terbaru langsung digunakan.',
        cameraUpdateLater: 'Nanti',
        cameraUpdateNow: 'Perbarui Sekarang',
        cameraBatteryWarning: 'Baterai sangat rendah. Mode hemat daya dapat membuat kamera patah-patah atau lambat. Matikan Mode Hemat Daya sementara jika kamera bermasalah.',
        cameraPerformanceWarning: 'Kamera berjalan sangat lambat. Coba matikan Mode Hemat Daya, tutup aplikasi kamera/Video Call lain, lalu coba lagi.',
        cameraBacklightWarning: 'Pencahayaan wajah terlalu gelap karena cahaya dari belakang. Silakan berputar agar wajah menghadap sumber cahaya dan hindari jendela terang di belakang.',
        offlineAttendanceSaved: 'Sinyal terputus. Absensi tetap disimpan di HP dan tidak membutuhkan internet.',
        attendanceQueuedForSync: 'Absensi tersimpan di HP. Pengiriman ke server akan dicoba otomatis saat internet tersedia kembali.',
        attendanceSyncSuccess: '{count} absensi tertunda berhasil disinkronkan ke server.',
        onlineRestored: 'Koneksi internet kembali.',
        cameraStartError: 'Kamera belum dapat dimulai. Periksa izin kamera browser.',
        suggestionDescription: 'Masukan untuk kelas piket,<br>dari guru maupun murid',
        teacherTab: '👩‍🏫 Guru',
        studentTab: '🎓 Murid',
        roleTeacher: 'Guru',
        roleStudent: 'Siswa',
        writeSuggestionTeacher: '✍️ Tulis Saran (Guru)',
        writeSuggestionStudent: '✍️ Tulis Saran (Murid)',
        optionalName: 'Nama (opsional)',
        yourName: 'Nama Anda',
        suggestionLabel: 'Saran / Masukan',
        suggestionPlaceholder: 'Tulis saran Anda di sini...',
        proofPhotoOptional: '📷 Foto bukti (opsional)',
        sendSuggestion: 'Kirim Saran',
        emptySuggestions: 'Belum ada saran.',
        proofAttached: '📎 Foto bukti terlampir',
        proofPhoto: 'Foto bukti',
        removePhoto: 'Hapus foto',
        suggestionEmptyError: 'Saran tidak boleh kosong.',
        suggestionInappropriate: 'Saran mengandung kata yang tidak pantas.\n\nMohon gunakan bahasa yang sopan.',
        suggestionPhotoProcessError: 'Foto bukti gagal diproses. Saran belum dikirim.\n\nSilakan pilih foto lain.',
        suggestionPhotoSaveError: 'Foto bukti tidak dapat disimpan. Saran belum dikirim.',
        suggestionSaveError: 'Saran tidak dapat disimpan di perangkat ini. Silakan coba lagi.',
        suggestionThanksWithPhoto: 'Terima kasih, saran dan foto bukti sudah tersimpan! 🙏',
        suggestionThanks: 'Terima kasih, saran Anda sudah tersimpan! 🙏',
        reportPhotoAlt: 'Foto bukti absensi',
        photoPreviewAlt: 'Pratinjau foto bukti',
        removeProofPhoto: 'Hapus foto',
        setupDesc: 'Pengaturan sistem pertama kali.<br>Daftarkan siswa dan foto wajah mereka.',
        infoClass: '🏫 Informasi Kelas',
        classLabel: 'Kelas',
        majorLabel: 'Jurusan',
        roomLabel: 'Ruangan',
        preference: '🌐 Bahasa',
        language: 'Bahasa',
        cameraRatio: 'Rasio Kamera',
        ratioHint: 'Pilih tampilan kamera yang kamu mau.',
        studentData: '👤 Data Siswa',
        activeDaysTitle: '📅 Hari Aktif Piket',
        activeDaysDesc: 'Pilih hari yang diperbolehkan untuk absensi piket.',
        backendApiLabel: 'URL Backend REST API (opsional)',
        backendApiPlaceholder: 'https://domain-sekolah.example/api',
        backendApiHelp: 'Kosongkan bila aplikasi tetap dipakai lokal. Isi URL backend bila Kotak Saran dan data sekolah ingin disinkronkan antar-perangkat.',
        storageStatusChecking: 'Memeriksa penyimpanan permanen…',
        storageStatusPersisted: 'Penyimpanan permanen aktif di browser ini.',
        storageStatusRequested: 'Permintaan penyimpanan permanen sudah dikirim ke browser.',
        storageStatusUnavailable: 'Browser tidak menyediakan API penyimpanan permanen.',
        backendStatusLocal: 'Sinkronisasi backend: belum dikonfigurasi (mode lokal).',
        backendStatusConfigured: 'Sinkronisasi backend: URL API sudah dikonfigurasi.',
        backendStatusError: 'Sinkronisasi backend: endpoint tidak dapat dihubungi; data lokal tetap dipakai sebagai antrean.',
        manualCameraOnly: 'Absensi hanya dapat dilakukan dengan kamera live perangkat. Unggah foto dari galeri dinonaktifkan.',
        addStudent: '+ Tambah Siswa',
        saveSettings: '💾 Simpan Pengaturan & Mulai',
        suggestions: '💬 Kotak Saran (Guru & Murid)',
        teacherRoom: '👨‍🏫 Ruang Guru — Laporan Absensi',
        deleteAll: 'Hapus Semua Data',
        cameraTitle: 'ABSENSI PIKET KELAS',
        cameraClassInfo: 'KELAS {class} {major} • RUANGAN {room}',
        checkingSchedule: 'Mengecek jadwal hari ini…',
        preparingAI: 'Mempersiapkan AI…',
        noDutyToday: '{day} - LIBUR PIKET 🎉',
        noScheduleToday: 'BELUM ADA JADWAL PIKET {day}',
        scheduleToday: 'JADWAL {day}: {names}',
        noFaceRecognized: 'Tidak ada wajah dikenali',
        aiReadySavedOne: 'AI SIAP! (1 Wajah Terdaftar)',
        aiReadySavedMany: 'AI SIAP! ({count} Wajah Terdaftar)',
        aiReadyNoPhotos: 'AI SIAP! Belum ada data wajah',
        aiLoadError: 'AI gagal dimuat. Periksa koneksi internet lalu coba lagi.',
        cameraUnavailable: 'Kamera tidak tersedia. Gunakan HTTPS atau localhost.',
        videoPlayError: 'Video kamera tidak dapat diputar otomatis. Tekan tombol Izinkan Akses Kamera lalu coba lagi.',
        allPresent: 'Semua hadir! 🎉',
        noDutyMembers: 'Belum ada anggota piket hari ini.',
        aiNotReady: 'AI belum siap atau belum ada foto wajah terdaftar.',
        proofCreateError: 'Foto bukti absensi gagal dibuat. Silakan coba lagi.',
        analysisError: 'AI gagal menganalisis kamera.\n\n{message}',
        photoSaveDataError: 'Data hasil absensi belum tersedia. Silakan ambil foto lagi.',
        reportSaveFailDetail: 'Laporan absensi gagal disimpan.\n\n{message}',
        teacherTitle: 'RUANG GURU',
        suggestionTitle: 'KOTAK SARAN',
        savePhoto: 'Simpan Foto',
        cancel: 'Batal',
        facePhoto: 'Daftar Foto Wajah',
        permission: 'Izinkan Akses Kamera',
        close: 'Tutup',
        reportReload: '↻ Muat Ulang Laporan',
        resultPresent: 'Piket: ',
        resultAbsent: 'Tidak Piket: ',
        success: 'Yeay! Absen Piket<br>Berhasil Disimpan ✨',
        pinLockedTitle: 'Ruang Guru Terkunci',
        pinDescription: 'Masukkan PIN untuk melihat laporan absensi dan foto bukti.',
        pinSetupTitle: 'Buat PIN Ruang Guru',
        pinSetupDescription: 'Ruang Guru belum punya PIN. Buat PIN 4–8 digit dulu.',
        pinLabel: 'PIN Guru',
        pinNewLabel: 'Buat PIN Guru',
        pinConfirmLabel: 'Konfirmasi PIN',
        pinCancel: 'Batal',
        pinOpen: 'Buka Ruang Guru',
        pinSaveOpen: 'Simpan PIN & Buka',
        pinMinPlaceholder: 'Minimal 4 digit',
        pinRepeatPlaceholder: 'Ulangi PIN',
        pinEnterPlaceholder: 'Masukkan PIN',
        pinNote: 'PIN ini melindungi Ruang Guru di perangkat ini. Untuk keamanan antar-perangkat, laporan perlu memakai login guru di server.',
        pinInvalid: 'PIN harus 4–8 digit.',
        pinMismatch: 'PIN tidak cocok.',
        pinWrong: 'PIN salah. Sisa percobaan: ',
        pinLocked: 'Terlalu banyak percobaan. Coba lagi dalam ',
        pinLockedDetail: 'Terlalu banyak percobaan. Coba lagi dalam {seconds} detik.',
        pinLockedSuffix: ' detik.',
        pinProcessError: 'PIN tidak bisa diproses. Cek penyimpanan browser lalu coba lagi.',
        reportWeekCurrent: 'Minggu ini',
        reportWeekPrevious: 'Minggu sebelumnya',
        reportWeekNext: 'Minggu berikutnya',
        reportWeekDays: 'Senin–Minggu',
        reportAvailable: '🔔 Laporan minggu ini tersedia. Guru bisa melihat foto bukti dan daftar Piket/Tidak Piket di bawah.',
        reportEmptySaturday: '🔔 Belum ada laporan absensi minggu ini yang tersimpan di perangkat ini.',
        reportGrowing: 'Laporan minggu ini akan bertambah setiap kali absensi hari itu disimpan.',
        reportArchive: 'Menampilkan arsip laporan untuk minggu yang dipilih.',
        reportNotSaved: 'BELUM ADA',
        reportNoData: 'Belum ada laporan absensi yang tersimpan untuk hari ini.',
        reportSaved: 'TERSIMPAN',
        reportNoRecognized: 'Tidak ada siswa yang dikenali',
        reportAllPresent: 'Semua siswa terjadwal terdeteksi',
        reportOnDuty: 'Piket:',
        reportNotOnDuty: 'Tidak Piket:',
        reportFaces: 'Wajah terdeteksi:',
        reportSchedule: 'Jadwal:',
        reportLoadingPhoto: 'Memuat foto bukti…',
        reportPhotoMissing: 'Foto bukti tidak ditemukan.',
        reportPhotoUnreadable: 'Foto bukti tidak bisa dibaca.',
        ratioSaveError: 'Rasio kamera tidak dapat disimpan.',
        languageSaveError: 'Bahasa tidak dapat disimpan.',
        teacherInfo: 'Laporan absensi piket kelas',
        classRoomInfo: 'Kelas',
        roomInfo: 'Ruangan',
        notConfigured: 'Pengaturan kelas belum selesai.',
        searchStudentPlaceholder: '🔍 Cari nama siswa...',
        noSearchResults: 'Nama siswa tidak ditemukan.',
        bulkAddStudent: '📋 Tambah Siswa Massal',
        bulkAddModalDesc: 'Tulis satu nama per baris, atau pisahkan dengan koma.',
        bulkAddPlaceholder: 'Ahmad Fauzi\nBunga Lestari\nCitra Dewi, Dewi Anggraini',
        bulkAddConfirm: 'Tambahkan',
        bulkAddCount: '{count} nama terdeteksi.',
        bulkAddOverLimit: '{count} nama terdeteksi, maksimal {max}.',
        bulkAddEmpty: 'Masukkan minimal satu nama siswa.',
        bulkAddLimit: 'Maksimal {count} nama per sekali tambah.',
        bulkAddResult: '{added} siswa ditambahkan. {skipped} dilewati karena sudah ada.',
        editStudent: 'Edit nama siswa',
        deleteStudent: 'Hapus siswa',
        studentDeleted: 'Siswa berhasil dihapus.',
        editStudentPrompt: 'Edit nama siswa:',
        editSaved: 'Nama siswa berhasil diubah.',
        editSaveError: 'Nama siswa gagal disimpan.\n\n{message}',
        bulkSaveError: 'Siswa massal gagal disimpan.\n\n{message}',
        clearSchedule: 'Bersihkan',
        clearScheduleConfirm: 'Kosongkan jadwal piket hari {day}?',
        clearScheduleSaved: 'Jadwal {day} sudah dikosongkan.',
        clearScheduleError: 'Jadwal gagal dibersihkan.\n\n{message}',
        flipCamera: 'Ganti kamera',
        cameraFront: 'Kamera depan',
        cameraBack: 'Kamera belakang',
        cameraSwitchError: 'Kamera tidak bisa diganti. Coba lagi.',
        faceTooFar: 'Wajah terlalu jauh. Dekatkan wajah ke kamera lalu coba lagi.',
        ttsNoFace: 'Tidak ada siswa yang terdeteksi.',
        ttsDuty: '{names} hadir piket.',
        exportCSV: '📦 Ekspor Laporan + Foto (ZIP)',
        exportEmpty: 'Belum ada laporan untuk diekspor.',
        exportSuccess: 'Laporan berhasil diekspor.',
        exportError: 'Laporan gagal diekspor.\n\n{message}',
        clearHistory: '🗑️ Hapus Riwayat Absensi',
        clearHistoryConfirm: 'Semua riwayat absensi dan foto buktinya akan dihapus permanen. Data siswa, foto wajah, dan jadwal tidak akan dihapus. Lanjutkan?',
        clearHistorySuccess: 'Riwayat absensi berhasil dibersihkan.',
        clearHistoryEmpty: 'Tidak ada riwayat absensi yang perlu dihapus.',
        clearHistoryError: 'Riwayat absensi gagal dibersihkan.\n\n{message}',
        dayMon: 'Senin',
        dayTue: 'Selasa',
        dayWed: 'Rabu',
        dayThu: 'Kamis',
        dayFri: 'Jumat',
        daySat: 'Sabtu',
        daySun: 'Minggu'
    },
    en: {
        appTitle: 'Class Duty Attendance',
        setupTitle: 'CLASS DUTY ATTENDANCE',
        setupStudentDesc: 'Add all students the system should recognize.\n                One clear face photo per student is enough.',
        promptAddStudent: 'Enter the student’s full name:',
        duplicateStudent: 'That student name is already on the list.',
        settingsNeedStudent: 'Add at least one student.',
        missingFaceConfirm: 'These students don’t have a face photo yet:\n\n{names}\n\nSave the settings anyway?',
        settingsNeedSchedule: 'Pick at least one student for the duty schedule.',
        settingsSaveError: 'The settings could not be saved to browser storage.\n\n{message}',
        settingsSavedToast: 'Settings saved. Opening camera…',
        flashUnsupported: 'This device does not support flash.',
        resumeAttendance: 'Your duty attendance is not finished yet.\n\nLet’s continue 🙂',
        openDbError: 'The browser database could not be opened.',
        sizeTooLarge: 'That photo is too large. Max 15 MB before compression.',
        exit: 'Exit',
        noStudents: 'No students yet.',
        photoRegistered: '✓ Face photo added',
        photoMissing: '⚠ No face photo yet',
        changePhoto: 'Change Photo',
        addPhoto: 'Add Photo',
        confirmDeleteStudent: 'Delete student "{name}"?',
        studentLabel: 'Student: {name}',
        chooseFacePhoto: 'Pick a face photo<br>with a 1:1 ratio',
        choosePhotoFirst: 'Pick a face photo first.',
        fileMustBeImage: 'The file needs to be an image.',
        processLoadAI: '⏳ Loading AI…',
        processPreparePhoto: '⏳ Getting the photo ready…',
        processAnalyzeFace: '⏳ Checking the face…',
        errorFaceNotDetected: 'No face was detected.',
        errorOneFace: 'The photo needs to show exactly one face.',
        errorEmbedding: 'The face embedding could not be created.',
        errorEmbeddingFormat: 'The face embedding format is invalid. Try saving the photo again.',
        errorFaceQuality: 'Face detection quality is too low.',
        errorPhotoRead: 'The browser could not read the photo.',
        errorPhotoProcess: 'The face could not be processed.',
        successPhoto: 'Face photo for {name} was added successfully. ✓',
        studentSetupRequired: 'Add students first.',
        noFacePhoto: '⚠ No face photo yet',
        cameraRatioAria: 'Camera ratio settings',
        ratioPortrait: '9:16 — Portrait',
        ratioLandscape: '16:9 — Landscape',
        emptySchedule: 'Add students first.',
        resultSave: 'Save & Done',
        savingReport: 'Saving report…',
        reportUnavailableNow: 'Attendance results are not ready yet. Take a photo again.',
        reportSaveError: 'The attendance report could not be saved.',
        resetWarningTitle: 'WARNING!',
        resetWarningBody: 'All student data, face photos, schedules, Teacher Room PIN, reports, and proof photos will be removed from this device.',
        resetContinue: 'Continue?',
        resetFacesBody: 'Student face data will also be removed.',
        resetConfirm: 'Are you sure you want to delete everything?',
        resetSuccess: 'All data has been deleted.',
        cameraErrorTitle: '📷 Camera is not ready yet',
        preparingCamera: 'Getting the camera ready…',
        cameraStartMessage: 'The camera could not start. Check your browser permission.',
        cameraErrorText: 'Allow camera access to continue attendance.',
        cameraClose: 'Close',
        cameraPermission: 'Allow Camera',
        cameraPermissionText: 'Camera permission is only available on HTTPS or localhost. A downloaded HTML file cannot bypass browser security restrictions.',
        cameraBusyError: 'The camera is being used by another app. End the WhatsApp/Zoom video call or close another camera app, then refresh this page.',
        cameraLegacyFallback: 'This browser does not provide the live camera API. Use a modern browser such as Chrome, Edge, or Safari, and open the app over HTTPS/localhost.',
        cameraPrivateMode: 'You may be using Incognito/Private Mode. Some offline and PWA features may not work normally.',
        cameraVirtualError: 'A virtual or fake camera was detected. Use the device hardware camera to continue attendance.',
        cameraPrivacyError: 'Privacy protection, an extension, or the browser blocked image capture. Turn off Shields/AdBlock for this page or use a main browser.',
        cameraIframeError: 'The camera is running inside an iframe. The parent school portal must allow camera access. Use allow="camera; autoplay; fullscreen".',
        cameraIframeTitle: 'Camera inside iframe',
        cameraIframeText: 'This app is running inside an iframe. The school portal must explicitly allow camera access on the iframe for live camera to work.',
        cameraUpdateTitle: 'A newer web version is available',
        cameraUpdateText: 'The latest attendance app version is ready. Update the page to use the newest changes.',
        cameraUpdateLater: 'Later',
        cameraUpdateNow: 'Update Now',
        cameraBatteryWarning: 'Battery is very low. Battery Saver may make the camera slow or choppy. Temporarily turn Battery Saver off if the camera has problems.',
        cameraPerformanceWarning: 'The camera is running very slowly. Try turning off Battery Saver, closing other camera/video-call apps, then try again.',
        cameraBacklightWarning: 'The face is too dark because of strong backlighting. Turn so your face faces the light and avoid having a bright window behind you.',
        offlineAttendanceSaved: 'The signal is gone. Your attendance is still saved on this phone and does not require internet.',
        attendanceQueuedForSync: 'Attendance is saved on this phone. Server delivery will retry automatically when internet is available.',
        attendanceSyncSuccess: '{count} queued attendance record(s) synced to the server.',
        onlineRestored: 'Internet connection restored.',
        cameraStartError: 'The camera could not start. Check your browser permission.',
        suggestionDescription: 'Share feedback about the duty class,<br>from teachers or students',
        teacherTab: '👩‍🏫 Teacher',
        studentTab: '🎓 Student',
        roleTeacher: 'Teacher',
        roleStudent: 'Student',
        writeSuggestionTeacher: '✍️ Write a suggestion (Teacher)',
        writeSuggestionStudent: '✍️ Write a suggestion (Student)',
        optionalName: 'Name (optional)',
        yourName: 'Your name',
        suggestionLabel: 'Suggestion / Feedback',
        suggestionPlaceholder: 'Write your suggestion here...',
        proofPhotoOptional: '📷 Proof photo (optional)',
        sendSuggestion: 'Send suggestion',
        emptySuggestions: 'No suggestions yet.',
        proofAttached: '📎 Proof photo attached',
        proofPhoto: 'Proof photo',
        removePhoto: 'Remove photo',
        suggestionEmptyError: 'Your suggestion cannot be empty.',
        suggestionInappropriate: 'Your suggestion contains language that is not allowed.\n\nPlease keep it respectful.',
        suggestionPhotoProcessError: 'The proof photo could not be processed. The suggestion was not sent.\n\nPlease pick another photo.',
        suggestionPhotoSaveError: 'The proof photo could not be saved. The suggestion was not sent.',
        suggestionSaveError: 'The suggestion could not be saved on this device. Try again.',
        suggestionThanksWithPhoto: 'Thanks! Your suggestion and proof photo have been saved. 🙏',
        suggestionThanks: 'Thanks! Your suggestion has been saved. 🙏',
        reportPhotoAlt: 'Attendance proof photo',
        photoPreviewAlt: 'Proof photo preview',
        removeProofPhoto: 'Remove photo',
        setupDesc: 'Let’s get things set up.<br>Add students and their face photos.',
        infoClass: '🏫 Class Info',
        classLabel: 'Class',
        majorLabel: 'Major',
        roomLabel: 'Room',
        preference: '🌐 Language',
        language: 'Language',
        cameraRatio: 'Camera ratio',
        ratioHint: 'Pick the camera shape you want.',
        studentData: '👤 Students',
        activeDaysTitle: '📅 Active Duty Days',
        activeDaysDesc: 'Choose which days are allowed for duty attendance.',
        backendApiLabel: 'REST API Backend URL (optional)',
        backendApiPlaceholder: 'https://school-domain.example/api',
        backendApiHelp: 'Leave blank for local-only use. Enter a backend URL to synchronize Suggestions and school data across devices.',
        storageStatusChecking: 'Checking persistent storage…',
        storageStatusPersisted: 'Persistent storage is active in this browser.',
        storageStatusRequested: 'A persistent-storage request has been sent to the browser.',
        storageStatusUnavailable: 'This browser does not provide the persistent-storage API.',
        backendStatusLocal: 'Backend sync: not configured (local mode).',
        backendStatusConfigured: 'Backend sync: API URL configured.',
        backendStatusError: 'Backend sync: endpoint could not be reached; local data remains in the queue.',
        manualCameraOnly: 'Attendance requires the device live camera. Gallery-photo upload is disabled.',

        addStudent: '+ Add a student',
        saveSettings: '💾 Save & Start',
        suggestions: '💬 Suggestions (Teachers & Students)',
        teacherRoom: '👨‍🏫 Teacher Room — Attendance',
        deleteAll: 'Delete Everything',
        cameraTitle: 'CLASS DUTY ATTENDANCE',
        cameraClassInfo: 'CLASS {class} {major} • ROOM {room}',
        checkingSchedule: 'Checking today’s schedule…',
        preparingAI: 'Getting the AI ready…',
        noDutyToday: '{day} — No duty today 🎉',
        noScheduleToday: 'NO DUTY SCHEDULED FOR {day}',
        scheduleToday: '{day} schedule: {names}',
        noFaceRecognized: 'No face recognized',
        aiReadySavedOne: 'AI is ready! (1 face saved)',
        aiReadySavedMany: 'AI is ready! ({count} faces saved)',
        aiReadyNoPhotos: 'AI is ready, but no face photos are saved yet.',
        aiLoadError: 'The AI could not load. Check your internet connection and try again.',
        cameraUnavailable: 'Camera not available. Use HTTPS or localhost.',
        videoPlayError: 'The camera video could not start automatically. Tap Allow Camera and try again.',
        allPresent: 'Everyone’s here! 🎉',
        noDutyMembers: 'There are no duty members scheduled today.',
        aiNotReady: 'The AI is not ready yet or no face photos have been added.',
        proofCreateError: 'The attendance proof photo could not be created. Try again.',
        analysisError: 'The AI could not analyze the camera.\n\n{message}',
        photoSaveDataError: 'The attendance result data is not ready yet. Take a photo again.',
        reportSaveFailDetail: 'The attendance report could not be saved.\n\n{message}',
        teacherTitle: 'TEACHER ROOM',
        suggestionTitle: 'SUGGESTION BOX',
        savePhoto: 'Save Photo',
        cancel: 'Cancel',
        facePhoto: 'Face Photos',
        permission: 'Turn on Camera',
        close: 'Close',
        reportReload: '↻ Refresh Reports',
        resultPresent: 'On duty: ',
        resultAbsent: 'Not on duty: ',
        success: 'Yay! Attendance<br>Saved ✨',
        pinLockedTitle: 'Teacher Room Locked',
        pinDescription: 'Enter the PIN to see attendance reports and photos.',
        pinSetupTitle: 'Set Up Teacher PIN',
        pinSetupDescription: 'There’s no Teacher Room PIN yet. Set a 4–8 digit PIN first.',
        pinLabel: 'Teacher PIN',
        pinNewLabel: 'New Teacher PIN',
        pinConfirmLabel: 'Confirm PIN',
        pinCancel: 'Cancel',
        pinOpen: 'Open Teacher Room',
        pinSaveOpen: 'Save PIN & Open',
        pinMinPlaceholder: 'At least 4 digits',
        pinRepeatPlaceholder: 'Enter it again',
        pinEnterPlaceholder: 'Enter PIN',
        pinNote: 'This PIN protects the Teacher Room on this device. For real multi-device security, reports need a server login.',
        pinInvalid: 'PIN must be 4–8 digits.',
        pinMismatch: 'The PINs don’t match.',
        pinWrong: 'Wrong PIN. Tries left: ',
        pinLocked: 'Too many tries. Try again in ',
        pinLockedDetail: 'Too many tries. Try again in {seconds} seconds.',
        pinLockedSuffix: ' seconds.',
        pinProcessError: 'Something went wrong with the PIN. Check your browser storage and try again.',
        reportWeekCurrent: 'This week',
        reportWeekPrevious: 'Previous week',
        reportWeekNext: 'Next week',
        reportWeekDays: 'Monday–Sunday',
        reportAvailable: '🔔 This week’s Monday–Friday report is ready. You can check the photos and the On duty/Not on duty list below.',
        reportEmptySaturday: '🔔 It’s Saturday. There are no Monday–Friday attendance reports saved on this device yet.',
        reportGrowing: 'This week’s report updates whenever that day’s attendance is saved.',
        reportArchive: 'Showing reports for the week you picked.',
        reportNotSaved: 'NOT YET',
        reportNoData: 'No attendance report has been saved for this day yet.',
        reportSaved: 'SAVED',
        reportNoRecognized: 'No students recognized',
        reportAllPresent: 'All scheduled students were detected',
        reportOnDuty: 'On duty:',
        reportNotOnDuty: 'Not on duty:',
        reportFaces: 'Faces detected:',
        reportSchedule: 'Schedule:',
        reportLoadingPhoto: 'Loading proof photo…',
        reportPhotoMissing: 'Attendance photo not found.',
        reportPhotoUnreadable: 'Couldn’t open the attendance photo.',
        ratioSaveError: 'Camera size could not be saved.',
        languageSaveError: 'Language could not be saved.',
        teacherInfo: 'Class duty attendance report',
        classRoomInfo: 'Class',
        roomInfo: 'Room',
        notConfigured: 'Class setup is not complete yet.',
        searchStudentPlaceholder: '🔍 Search students...',
        noSearchResults: 'No students found.',
        bulkAddStudent: '📋 Add Students in Bulk',
        bulkAddModalDesc: 'Write one name per line, or separate them with commas.',
        bulkAddPlaceholder: 'Ahmad Fauzi\nBunga Lestari\nCitra Dewi, Dewi Anggraini',
        bulkAddConfirm: 'Add',
        bulkAddCount: '{count} names detected.',
        bulkAddOverLimit: '{count} names detected, {max} max.',
        bulkAddEmpty: 'Enter at least one student name.',
        bulkAddLimit: 'You can add up to {count} names at once.',
        bulkAddResult: '{added} students added. {skipped} skipped because they were already on the list.',
        editStudent: 'Edit student name',
        deleteStudent: 'Delete student',
        studentDeleted: 'Student deleted.',
        editStudentPrompt: 'Edit student name:',
        editSaved: 'Student name updated.',
        editSaveError: 'The student name could not be saved.\n\n{message}',
        bulkSaveError: 'The students could not be saved.\n\n{message}',
        clearSchedule: 'Clear',
        clearScheduleConfirm: 'Clear the duty schedule for {day}?',
        clearScheduleSaved: '{day} schedule cleared.',
        clearScheduleError: 'The schedule could not be cleared.\n\n{message}',
        flipCamera: 'Switch camera',
        cameraFront: 'Front camera',
        cameraBack: 'Back camera',
        cameraSwitchError: 'Couldn’t switch the camera. Try again.',
        faceTooFar: 'Your face is too far away. Move closer and try again.',
        ttsNoFace: 'No student was detected.',
        ttsDuty: 'On duty: {names}.',
        exportCSV: '📦 Export Report + Photos (ZIP)',
        exportEmpty: 'There are no reports to export yet.',
        exportSuccess: 'Report exported.',
        exportError: 'The report could not be exported.\n\n{message}',
        clearHistory: '🗑️ Clear Attendance History',
        clearHistoryConfirm: 'All attendance history and proof photos will be permanently deleted. Student data, face photos, and schedules will stay. Continue?',
        clearHistorySuccess: 'Attendance history cleared.',
        clearHistoryEmpty: 'There is no attendance history to clear.',
        clearHistoryError: 'Attendance history could not be cleared.\n\n{message}',
        dayMon: 'Monday',
        dayTue: 'Tuesday',
        dayWed: 'Wednesday',
        dayThu: 'Thursday',
        dayFri: 'Friday',
        daySat: 'Saturday',
        daySun: 'Sunday'
    }
};

function t(key, lang = null) {
    const resolvedLang = lang === 'en'
        ? 'en'
        : lang === 'id'
            ? 'id'
            : (typeof konfigurasi !== 'undefined' && konfigurasi?.bahasa === 'en' ? 'en' : 'id');
    return TRANSLATIONS[resolvedLang]?.[key] ?? TRANSLATIONS.id?.[key] ?? key;
}


function replaceTemplate(text, data = {}) {
    const source = String(text ?? '');
    return source.replace(/{(\w+)}/g, (match, key) => {
        const value = data?.[key];
        return value === undefined || value === null ? match : String(value);
    });
}


function onDomReady(callback) {
    if (typeof callback !== 'function') return;
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', callback, { once: true });
    } else {
        callback();
    }
}
